#!/usr/bin/env zsh
emulate -L zsh
# setopt extended_glob warn_create_global typeset_silent \
#         no_short_loops rc_quotes no_auto_pushd
# unload the plugin
eval "$(zsh -- "${SCRIPTS_LIB_DIR}/bootstrap.sh" --unload)"

