name:  Job
description: >
  Inject BitFlight's shell-scripts as bash functions
  into the Github Action's Job environment, via the BASH_ENV
outputs:
  loaded:
    value: ${{ steps.bash_functions.outputs.loaded }}
  path:
    value: ${{ steps.bash_functions.outputs.path }}
env:
  SHELL_SCRIPTS_GITHUB_REPOSITORY: 'bitflight-devops/shell-scripts'

runs:
  using: 'composite'
  steps:
    - name: Set ENV details
      id: version
      shell: bash
      run: |
        BFD_REPOSITORY="${{ github.action_path }}"
        echo "BFD_REPOSITORY=${BFD_REPOSITORY}" >>"${GITHUB_ENV}"
        SCRIPTS_LIB_DIR="${BFD_REPOSITORY}/lib"
        echo "SCRIPTS_LIB_DIR=${SCRIPTS_LIB_DIR}" >>"${GITHUB_ENV}"

    - name: Publish Bash Functions To Job Steps
      id: bash_functions
      if: steps.version.outputs.current_version_loaded == 'false'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        export SHELL_SCRIPTS_QUIET=1
        export NONINTERACTIVE=1
        bash -- "${SCRIPTS_LIB_DIR}/bootstrap.sh" --silent > ./bash_env.sh
        export "BASH_ENV=${SCRIPTS_LIB_DIR}/bash_env.sh"
        chmod +x "${BASH_ENV}"
        source "${BASH_ENV}"
        echo "BASH_ENV=${BASH_ENV}" >> "${GITHUB_ENV}"
        debug BFD_REPOSITORY=${BFD_REPOSITORY}"
        debug SCRIPTS_LIB_DIR=${SCRIPTS_LIB_DIR}"
        debug BOOTSTRAP=${BOOTSTRAP}"
        debug SHELL_SCRIPTS_QUIET=${SHELL_SCRIPTS_QUIET}"
        debug NONINTERACTIVE=${NONINTERACTIVE}"
        debug BASH_ENV=${BASH_ENV}"
        debug BFD_SHELL_SCRIPTS_VERSION=${BFD_SHELL_SCRIPTS_VERSION}"

