name: Load common bash functions
description: >
  Loads common bash functions used by other actions.
outputs:
  loaded:
    value: ${{ steps.bash_functions.outputs.loaded }}
  path:
    value: ${{ steps.bash_functions.outputs.path }}
env:
  SHELL_SCRIPTS_GITHUB_REPOSITORY: 'bitflight-devops/shell-scripts'

runs:
  using: 'composite'
  steps:
    - name: Get Version To Checkout
      id: version
      shell: bash
      run: |
        BFD_REPOSITORY="${{ github.action_path }}"
        echo "BFD_REPOSITORY=${BFD_REPOSITORY}" >>"${GITHUB_ENV}"

    - name: Publish Bash Functions To Job Steps
      id: bash_functions
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        NONINTERACTIVE=1 SHELL_SCRIPTS_QUIET=1 source "lib/bootstrap.sh"
        set_env BOOTSTRAP "${BFD_REPOSITORY}/lib/bootstrap.sh"
        set_env SHELL_SCRIPTS_QUIET "1"
        set_env NONINTERACTIVE "1"
        set_output path "${BOOTSTRAP}"
        if [ -z "${BASH_ENV:-}" ]; then
          set_env "BASH_ENV" "${BOOTSTRAP}"
          echo "Loaded Bash Functions to BASH_ENV"
          set_output loaded "true"
        else
          set_output loaded "false"
        fi
