name:  Job
description: >
  Inject BitFlight's shell-scripts as bash functions
  into the Github Action's Job environment, via the BASH_ENV
outputs:
  loaded:
    value: ${{ steps.bash_functions.outputs.loaded }}
  path:
    value: ${{ steps.bash_functions.outputs.path }}
env:
  SHELL_SCRIPTS_GITHUB_REPOSITORY: 'bitflight-devops/shell-scripts'

runs:
  using: 'composite'
  steps:
    - name: Get Version To Checkout
      id: version
      shell: bash
      run: |
        version=$(git -C "${{ github.action_path }}" describe --all 2>/dev/null || true)
        current_version_loaded='false'
        if [[ -z ${BFD_SHELL_SCRIPTS_VERSION:-} ]]; then
          echo "::debug ::BFD_SHELL_SCRIPTS_VERSION is not set, using current checkout"
          BFD_SHELL_SCRIPTS_VERSION="${version}"
          echo "BFD_SHELL_SCRIPTS_VERSION=${version}" >> "${GITHUB_ENV}"
        elif [[ "${BFD_SHELL_SCRIPTS_VERSION}" != "${version}" ]]; then
          echo "::debug ::BFD_SHELL_SCRIPTS_VERSION is already set to ${BFD_SHELL_SCRIPTS_VERSION}"
          echo "::debug ::and this BFD_SHELL_SCRIPTS_VERSION version is ${version}"
          echo "::debug ::this may cause unexpected behavior"
        elif [[ "${BASH_ENV}" == "${{ inputs.created_source_file_path }}" ]]; then
          echo "::debug ::BFD_SHELL_SCRIPTS_VERSION is already set to ${BFD_SHELL_SCRIPTS_VERSION}"
          current_version_loaded='true'
        fi
        echo "current_version_loaded=${current_version_loaded}" >> "${GITHUB_OUTPUT}"
        BFD_REPOSITORY="${{ github.action_path }}"
        echo "BFD_REPOSITORY=${BFD_REPOSITORY}" >>"${GITHUB_ENV}"
        SCRIPTS_LIB_DIR="${BFD_REPOSITORY}/lib"
        echo "SCRIPTS_LIB_DIR=${SCRIPTS_LIB_DIR}" >>"${GITHUB_ENV}"
        echo "Shell Scripts Version: ${BFD_SHELL_SCRIPTS_VERSION}"

    - name: Publish Bash Functions To Job Steps
      id: bash_functions
      if: steps.version.outputs.current_version_loaded == 'false'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        source "${SCRIPTS_LIB_DIR}/bootstrap.sh"
        set_env BOOTSTRAP "${SCRIPTS_LIB_DIR}/bootstrap.sh"
        set_env SHELL_SCRIPTS_QUIET "1"
        set_env NONINTERACTIVE "1"
        set_env "BASH_ENV" "${BOOTSTRAP}"
        echo "Loaded Bash Functions to BASH_ENV"
        if [[ ${{github.debug}} == 'true' ]]; then
          echo "::debug ::BFD_REPOSITORY=${BFD_REPOSITORY}"
          echo "::debug ::SCRIPTS_LIB_DIR=${SCRIPTS_LIB_DIR}"
          echo "::debug ::BOOTSTRAP=${BOOTSTRAP}"
          echo "::debug ::SHELL_SCRIPTS_QUIET=${SHELL_SCRIPTS_QUIET}"
          echo "::debug ::NONINTERACTIVE=${NONINTERACTIVE}"
          echo "::debug ::BASH_ENV=${BASH_ENV}"
          echo "::debug ::BFD_SHELL_SCRIPTS_VERSION=${BFD_SHELL_SCRIPTS_VERSION}"
        fi
