name: Test
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
  unit-test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run ShUnit tests
        run: |
          tests/run.sh

  installer-test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run ShUnit tests
        run: |
          NONINTERACTIVE=1 source <(curl -sL "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}/install.sh")
          eval $(bash -- "$BFD_REPOSITORY/lib/bootstrap.sh")
